name: Check Flake

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --override-input nix-devshells github:kleinbem/nix-devshells
      - run: nix fmt --override-input nix-devshells github:kleinbem/nix-devshells -- --fail-on-change
